### PR TITLE
Page a full screenwidth down on space

### PR DESCRIPTION
**Pull request by snan**
and up on b. Just like less. Just a suggestion.

### CODE REVIEW

**Comment by codesoap** [comment]
Thanks for your input! I think this is a good addition, but there is a potential conflict: I'm probably going to add key bindings for exiting with a given forward- or back-link. Good key bindings for those would be `f` and `b`, so I'll try to make up my mind about whether I prefer compatibility with less or an intuitive key for going back.

**Comment by snan** [comment]
Ctrl-B for back, b for up 🤷🏻‍♀️

**Comment by snan** [comment]
GI'm more used to h for back, l for forward (even though I don't use vi 
bindings normally)

**Comment by codesoap** [comment]
I have decided to prioritize compatibility with less and added the key bindings for `b`, `Space` and also `f` for scrolling: https://github.com/codesoap/gmir/commit/228991d3272ed9733ac7623b07a5414a51726f56

`v.Scroll(s, height-1)` had to be used instead of `v.Scroll(s, height)`, because the bar at the bottom reduces the page size by one row.

I had thought about using `h` and `l` for going forward and back in the history, but decided to use `h` for scrolling to the next heading instead. I might also use `l` for scrolling right (on wide preformatted text) later on. I don't like Ctrl-B for going back, because it will potentially be something that users do a lot, so I want it to be a single key press. I'll probably just use some other letter, like `z`.

**Pull request closed without merging**
